"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Circle, Clock3, Pause, Play, RefreshCw, RotateCcw, Search } from "lucide-react";
import { controlWorkflow, fetchApprovals, fetchTask, fetchWorkflows } from "@/lib/api";

interface Stage { key: string; label: string; state: string }
interface NodeItem { id: string; dispatch_id: string; route_to: string; status: string; review_status: string; result_path: string; mtime_str?: string }
interface Workflow { dispatch_id: string; created_at?: string; queue_started_at?: string; queue_finished_at?: string; title: string; supervisor_status: string; current_stage: string; latest_verdict: string; failure_reason: string; result_path: string; queue_status: string; queue_process_alive: boolean; queue_process_id: number|null; last_queue_event: string; updated_at: number; stages: Stage[]; nodes: NodeItem[] }
interface TaskDetail { id: string; files: Record<string,string> }
interface Approval { task_id: string; status: string; reason: string; summary_for_josh: string; artifact_path: string; josh_action_required: boolean }
const fmtTs = (value?: string) => value ? value.slice(0, 19).replace("T", " ") : "";
const colors: Record<string,string> = { completed:"border-emerald-600 bg-emerald-950 text-emerald-200", processing:"border-amber-600 bg-amber-950 text-amber-200", blocked:"border-red-700 bg-red-950 text-red-200", pending:"border-zinc-700 bg-zinc-900 text-zinc-500", skipped:"border-zinc-800 bg-zinc-950 text-zinc-700" };
function StageIcon({state}:{state:string}) { if(state==="completed") return <CheckCircle2 size={13}/>; if(state==="processing") return <Clock3 size={13}/>; if(state==="blocked") return <AlertTriangle size={13}/>; return <Circle size={11}/> }

export default function DispatchFlow() {
  const [items,setItems]=useState<Workflow[]>([]); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const [nodeId,setNodeId]=useState<string|null>(null); const [detail,setDetail]=useState<TaskDetail|null>(null); const [fileName,setFileName]=useState<string>(""); const [approvals,setApprovals]=useState<Approval[]>([]);
  const refresh=useCallback(async()=>{const [data,approvalData]=await Promise.all([fetchWorkflows(),fetchApprovals()]);setItems(Array.isArray(data)?data:[]);setApprovals(Array.isArray(approvalData.items)?approvalData.items:[])},[]);
  useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0);const timer=window.setInterval(()=>void refresh(),10000);return()=>{clearTimeout(initial);clearInterval(timer)}},[refresh]);
  const visible=useMemo(()=>{const value=query.trim().toLowerCase();return items.filter(item=>!value||item.dispatch_id.toLowerCase().includes(value)||item.title.toLowerCase().includes(value)).slice(0,30)},[items,query]);
  const workflow=visible.find(item=>item.dispatch_id===selected)??visible[0]??null;
  const workflowApprovals=workflow?approvals.filter(item=>item.task_id===workflow.dispatch_id||item.task_id.startsWith(`${workflow.dispatch_id}-`)):[];
  const inspectNode=async(id:string)=>{setNodeId(id);const data=await fetchTask(id);const safeDetail={id:data.id??id,files:data.files??{}};setDetail(safeDetail);const names=Object.keys(safeDetail.files);setFileName(names.find((name)=>name.endsWith("RESULT.md"))??names.find((name)=>name.endsWith("WORKER_STATUS.md"))??names.find((name)=>name.endsWith("AGENT_OUTPUT.md"))??names[0]??"")};
  const act=async(action:"pause"|"resume"|"retry")=>{if(!workflow||!window.confirm(`${action} ${workflow.dispatch_id}?`))return;setBusy(true);try{await controlWorkflow(workflow.dispatch_id,action);await refresh()}finally{setBusy(false)}};
  return <div className="grid min-h-[620px] gap-4 xl:grid-cols-[320px_minmax(0,1fr)]">
    <aside className="border-r border-zinc-800 pr-4"><div className="flex items-center gap-2 border border-zinc-800 bg-zinc-900 px-3 py-2"><Search size={13} className="text-zinc-500"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Dispatch ID or title" className="min-w-0 flex-1 bg-transparent text-xs outline-none"/><button onClick={()=>void refresh()} title="Refresh"><RefreshCw size={13}/></button></div>
      <div className="mt-3 max-h-[70vh] divide-y divide-zinc-800 overflow-y-auto border-y border-zinc-800">{visible.map(item=><button key={item.dispatch_id} onClick={()=>setSelected(item.dispatch_id)} className={`w-full px-3 py-3 text-left ${workflow?.dispatch_id===item.dispatch_id?"bg-zinc-800":"hover:bg-zinc-900"}`}><p className="truncate text-[11px] font-medium">{item.title}</p><p className="mt-1 truncate font-mono text-[9px] text-zinc-500">{item.dispatch_id}</p><p className="mt-1 text-[9px] text-zinc-400">{item.supervisor_status} · {item.nodes.length} nodes</p></button>)}</div></aside>
    <section className="min-w-0">{workflow?<><header className="flex flex-wrap items-start gap-3 border-b border-zinc-800 pb-3"><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{workflow.title}</h2><p className="mt-1 break-all font-mono text-[9px] text-zinc-500">{workflow.dispatch_id}</p>
        <p className="mt-1 font-mono text-[9px] text-zinc-400">開單(Telegram) {workflow.created_at || "unknown"}{workflow.queue_started_at && <> · 開跑 {fmtTs(workflow.queue_started_at)}</>}{workflow.queue_finished_at && <> · 結束 {fmtTs(workflow.queue_finished_at)}</>}</p></div><span className="border border-zinc-700 px-2 py-1 text-[10px]">{workflow.supervisor_status}</span></header>
      <div className="grid gap-3 py-5 md:grid-cols-3 xl:grid-cols-6">{workflow.stages.map((stage,index)=><div key={stage.key} className="relative"><div className={`min-h-20 border p-3 ${colors[stage.state]??colors.pending}`}><StageIcon state={stage.state}/><p className="mt-2 text-[10px] font-medium">{stage.label}</p><p className="mt-1 text-[9px] opacity-70">{stage.state}</p></div>{index<workflow.stages.length-1&&<span className="absolute -right-3 top-9 hidden text-zinc-600 xl:block">→</span>}</div>)}</div>
      <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]"><div><h3 className="mb-2 text-[11px] font-semibold">Execution nodes</h3><div className="divide-y divide-zinc-800 border-y border-zinc-800">{workflow.nodes.map(node=><button onClick={()=>void inspectNode(node.dispatch_id)} key={node.dispatch_id} className={`grid w-full gap-1 px-2 py-2 text-left text-[10px] hover:bg-zinc-900 sm:grid-cols-[90px_120px_minmax(0,1fr)_110px] ${nodeId===node.dispatch_id?"bg-zinc-900":""}`}><span>{node.status}</span><span className="text-zinc-500">{node.route_to||"unlabeled"}</span><div className="min-w-0"><p className="truncate font-mono" title={node.dispatch_id}>{node.dispatch_id}</p>{node.result_path&&<p className="truncate text-[9px] text-zinc-600" title={node.result_path}>{node.result_path}</p>}</div><span className="text-right font-mono text-[9px] text-zinc-500">{node.mtime_str||""}</span></button>)}</div></div>
        <aside className="border-l border-zinc-800 pl-4 text-[10px]"><h3 className="font-semibold">Current evidence</h3><div className="mt-3 space-y-2 text-zinc-500"><p>stage: {workflow.current_stage}</p><p>verdict: {workflow.latest_verdict||"none"}</p><p>queue: {workflow.queue_process_alive?`running PID ${workflow.queue_process_id}`:workflow.queue_status}</p>{workflow.failure_reason&&<p className="text-red-300">{workflow.failure_reason}</p>}{workflow.last_queue_event&&<p className="break-words font-mono text-[9px]">{workflow.last_queue_event}</p>}</div><div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>void act("pause")} title="Pause" className="border border-zinc-700 p-2"><Pause size={12}/></button><button disabled={busy} onClick={()=>void act("resume")} title="Resume" className="border border-zinc-700 p-2"><Play size={12}/></button><button disabled={busy} onClick={()=>void act("retry")} title="Retry" className="border border-zinc-700 p-2"><RotateCcw size={12}/></button></div></aside></div>
      {workflowApprovals.length>0&&<section className="mt-5 border-t border-zinc-800 pt-4"><h3 className="text-[11px] font-semibold">Approvals</h3>{workflowApprovals.map(item=><div key={item.artifact_path} className="mt-2 border-l-2 border-amber-700 pl-3 text-[10px]"><p>{item.status} · {item.reason}</p><p className="mt-1 text-zinc-500">{item.summary_for_josh}</p><p className="mt-1 truncate font-mono text-[9px] text-zinc-600">{item.artifact_path}</p></div>)}</section>}
      {detail&&<section className="mt-5 border-t border-zinc-800 pt-4"><div className="flex flex-wrap items-center gap-2"><h3 className="mr-auto text-[11px] font-semibold">Task output · {detail.id}</h3>{Object.keys(detail.files).map(name=><button key={name} onClick={()=>setFileName(name)} className={`px-2 py-1 text-[9px] ${fileName===name?"bg-zinc-700":"bg-zinc-900 text-zinc-500"}`}>{name.replace("OUTPUTS\\","")}</button>)}</div><pre className="mt-3 max-h-[420px] overflow-auto whitespace-pre-wrap break-words border border-zinc-800 bg-black/30 p-3 text-[10px] text-zinc-300">{detail.files[fileName]??"No output content"}</pre></section>}
    </>:<p className="text-sm text-zinc-500">No matching dispatch.</p>}</section>
  </div>;
}
