[CmdletBinding()]
param([string]$AgentOSRoot, [switch]$Check)
$ErrorActionPreference = "Stop"
if (-not $AgentOSRoot) { $AgentOSRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot) }
$root = (Resolve-Path $AgentOSRoot).Path
$registry = [IO.File]::ReadAllText((Join-Path $root "config\script_registry.json"), [Text.Encoding]::UTF8) | ConvertFrom-Json
$lines = [Collections.Generic.List[string]]::new()
$lines.Add("# AgentOS Executable Registry")
$lines.Add("")
$lines.Add("Generated from `config/script_registry.json`. Do not edit this file by hand.")
$lines.Add("")
$lines.Add("| Category | ID | Purpose | Path | Mode | Risk | Enabled |")
$lines.Add("| --- | --- | --- | --- | --- | --- | --- |")
$tick = [char]96
foreach ($item in @($registry.entries | Sort-Object category,id)) {
    $lines.Add("| $($item.category) | $tick$($item.id)$tick | $($item.display_name) | $tick$($item.implementation_path)$tick | $($item.start_mode) | $($item.risk) | $($item.enabled.ToString().ToLowerInvariant()) |")
}
$expected = ($lines -join "`n") + "`n"
$path = Join-Path $root "scripts\REGISTRY.md"
if ($Check) {
    if (-not (Test-Path $path) -or [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8) -ne $expected) { throw "scripts/REGISTRY.md is stale; run generate-registry-readme.ps1" }
    "registry_readme_status=PASS"; exit 0
}
[IO.File]::WriteAllText($path, $expected, [Text.UTF8Encoding]::new($false))
"registry_readme_status=GENERATED"; "entry_count=$(@($registry.entries).Count)"
