[CmdletBinding()]
param(
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$MachineId,
    [string]$RepositoryUrl = "https://github.com/Josh404DR/AgentOS.git",
    [string]$TargetParent = (Join-Path $env:USERPROFILE "AgentOS-acceptance"),
    [switch]$ExecuteExternalDrill
)

$ErrorActionPreference = "Stop"
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$taskName = "machine-acceptance-$MachineId-$timestamp"
$target = Join-Path ([IO.Path]::GetFullPath($TargetParent)) $taskName

if (-not $ExecuteExternalDrill) {
    Write-Output "machine_acceptance_status=READY"
    Write-Output "external_changes=false"
    Write-Output "target=$target"
    Write-Output "rerun_with=-ExecuteExternalDrill"
    exit 0
}

foreach ($command in @("git.exe", "gh.exe", "powershell.exe")) {
    if (-not (Get-Command $command -ErrorAction SilentlyContinue)) { throw "Required command missing: $command" }
}
& gh.exe auth status | Out-Null
if ($LASTEXITCODE -ne 0) { throw "GitHub CLI is not authenticated for the machine-acceptance drill." }
if (Test-Path -LiteralPath $target) { throw "Acceptance target already exists; refusing to overwrite it: $target" }
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target) | Out-Null

$result = [ordered]@{
    schema_version = "1.0.0"
    machine_id = $MachineId
    machine_identity = [Security.Principal.WindowsIdentity]::GetCurrent().Name
    repository_url = $RepositoryUrl
    target = $target
    started_at = (Get-Date).ToString("o")
    branch = $null
    pull_request = $null
    status = "running"
}

try {
    & git.exe clone -- $RepositoryUrl $target
    if ($LASTEXITCODE -ne 0) { throw "Fresh clone failed." }
    Push-Location $target
    try {
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts\entrypoints\agentos-bootstrap-check.ps1 -AgentOSRoot $target
        if ($LASTEXITCODE -ne 0) { throw "Fresh-clone bootstrap prerequisites failed." }
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File dashboard\start.ps1 -Install
        if ($LASTEXITCODE -ne 0) { throw "Fresh-clone dependency installation failed." }
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts\entrypoints\agentos-work-start.ps1 -TaskName $taskName
        if ($LASTEXITCODE -ne 0) { throw "Guarded work start failed." }

        $branch = "codex/$taskName"
        $fixtureRelative = "tests/fixtures/$taskName.txt"
        $fixturePath = Join-Path $target ($fixtureRelative -replace '/', '\')
        [IO.File]::WriteAllText($fixturePath, "machine_id=$MachineId`ncreated_at=$((Get-Date).ToString('o'))`n", [Text.UTF8Encoding]::new($false))
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts\entrypoints\agentos-check.ps1
        if ($LASTEXITCODE -ne 0) { throw "Machine acceptance local gate failed." }
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts\entrypoints\agentos-work-finish.ps1 -Files $fixtureRelative -Message "test: record $MachineId acceptance drill" -Push
        if ($LASTEXITCODE -ne 0) { throw "Guarded work finish or push failed." }

        $prUrl = (& gh.exe pr create --repo Josh404DR/AgentOS --base master --head $branch --title "test: $MachineId acceptance drill" --body "Two-machine workflow acceptance fixture generated by agentos-machine-acceptance.ps1. No runtime state or credentials are included.").Trim()
        if ($LASTEXITCODE -ne 0 -or -not $prUrl) { throw "Acceptance pull request creation failed." }
        $result.branch = $branch
        $result.pull_request = $prUrl
        $result.status = "PASS"
    } finally {
        Pop-Location
    }
} catch {
    $result.status = "FAIL"
    $result.error = $_.Exception.Message
    throw
} finally {
    $result.finished_at = (Get-Date).ToString("o")
    if (Test-Path -LiteralPath $target -PathType Container) {
        $evidenceDir = Join-Path $target "data\machine_acceptance"
        New-Item -ItemType Directory -Force -Path $evidenceDir | Out-Null
        $evidencePath = Join-Path $evidenceDir "$MachineId.json"
        [IO.File]::WriteAllText($evidencePath, ($result | ConvertTo-Json -Depth 6), [Text.UTF8Encoding]::new($false))
        Write-Output "evidence_path=$evidencePath"
    }
}

Write-Output "machine_acceptance_status=PASS"
Write-Output "branch=$($result.branch)"
Write-Output "pull_request=$($result.pull_request)"
